name: Run Build Tests
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - dev
  workflow_dispatch:

jobs:
  build_tests:
    strategy:
      max-parallel: 2
      matrix:
        python-version: [ 3.7, 3.8, 3.9, "3.10" ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Build Tools
        run: |
          python -m pip install build wheel
      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt install python3-dev swig libssl-dev
      - name: Build Source Packages
        run: |
          python setup.py sdist
      - name: Build Distribution Packages
        run: |
          python setup.py bdist_wheel
      - name: Install repo
        run: |
          pip install .
      - uses: pypa/gh-action-pip-audit@v1.0.8
        with:
            # Ignore irrelevant Mercurial vulnerability
            # Ignore `requests` and `urllib3` vulnerabilities as they are not used in this package
            # Ignore `setuptools` and `pip` vulnerabilities  I don't think they apply here
            ignore-vulns: |
                PYSEC-2023-228
                GHSA-9wx4-h78v-vm56
                GHSA-34jh-p97f-mpxf
                PYSEC-2022-43012
